### ISSUE TITLE
There's no license for the code

### ISSUE THREAD

**Issue by Titousensei** [skullb0x/bluesaga#1]
The license file mentions images and music, but nothing about the code itself. What is it?

**Comment by skullb0x** [comment]
Hi Eric!

As you can see I am new to github, I don't really know what license to use
for the code. What I want is that anyone can change/add/remove code from
the project as long as it stays in the bluesaga project. So people can
create new branches and make their own version of Blue Saga but not just
take all the code and create another game called something else if you know
what I mean.

Do you know what license that is? In that case I can update the LICENSE
document.

Thanks for the help!
/Jonathan

2016-07-30 5:30 GMT+02:00 Eric Gaudet notifications@github.com:

**Comment by Titousensei** [comment]
You basically have two options. 

1) No license: you retain copyright for all the code. People can read it and modify it for themselves, but to use it (publicly) they need your authorization. You keep all the control but this is also the most restrictive - it can limit the number of external contributions. This is what you have now because you did not explicitly give any license. (It will be better to say it explicitly: The code is copyrighted by the following people: ...; To use the code, you must contact the author directly and ask permission.)

2) GPL: everybody can basically do what they want with the code, but they must publish the source under GPL too, so even if they don't cooperate you can get their own modifications and include them back to your code base. This is to build a community where everybody contributes to a better codebase, but you can't prevent people from forking completely different projects.

It's a difficult choice. You can always go from 1) now to 2) later.

But I think there's more things to consider: I forked the code with github and I started changing things. I will to contribute back with bug fixes and such. But at some point I will add features I like and you don't or you don't have time to fully review. Maybe at the same time you will add features I don't like. At this point I will have a version of bluesaga that is different from yours. Are they still the same project? Let's say I add a new class of characters, can the player go back to your server? I'm not sure what the definition of "the bluesaga project" is. One example of that is the linux kernel: it's under GPL, anybody can patch it and sell their own version, but Linus and his team are keeping track of all those changes to integrate them back into their "official" kernel.

I feel that the discussion would be easier if the code base was split into functional pieces: the network layer could be LGPL (library is GPL but can be included in private code), the world engine could be GPL, and the bluesaga project (images, music, maps, code for abilities and classes) could be copyrighted. That would require significant code surgery, but I feel some of it needs to happen anyway to make the code more contribution-friendly. (example: I already added ant for compilation, removed the checked-in .class files, and changed some of the formatting.)

The question is: how much code changes are you will/able to review and integrate?

**Comment by skullb0x** [comment]
Thank you for your great explanation!

So basically what I want with this whole project is that anyone can make
their own version of Blue Saga, like a remix of a song, so they can add
stuff, change the rules as long as the game is still called Blue Saga and
the community is still connected to the website with login and so on.

I saw your response to Awlast, it is great if you somehow can make let me
know if you fixed general bugs that can be perhaps be merged to the master
server.

/Jonathan

2016-07-30 19:27 GMT+02:00 Eric Gaudet notifications@github.com:

**Comment by Titousensei** [comment]
You might have to make the code GPL, because it incudes NameGenerator which is itself GPL (so by this GPL license you're require to provide the source code under GPL). The alternatives are to replace NameGenerator with another non-GPL class, or to contact the author and ask him to re-license it for you.

Another issue with GPL is that bs_user.jar is not open source. This is not a big issue because you're unlikely to sue yourself :-)

I don't see a good license to make sure the game is still connected. Keeping no license means all the pull requests are basically donations and you own all the rights, so that might deter people from contributing.

Maybe it's too early to decide. I like the GPL myself, because I feel that the Blue Saga name is associated with the art and the story (BTW dude, you should totally look into making some stuffed toys and action figures!), not so much the engine. But on the other hand it's hard to know what customizations will come up. 

My recommendation is to keep the code without a license for now until there's enough activity to get a better sense of the landscape, and re-assess. (Or GPL with the added clause that bs_user.jar must be used unchanged and the name Blue Saga must be in the title.)

**Comment by skullb0x** [comment]
I've removed NameGenerator as it wasn't used anywhere.
