### ISSUE TITLE
Delete .project and .classpath from .gitignore

### ISSUE THREAD

**Issue by Oen44** [skullb0x/bluesaga#16]
Can you do that? There is no way to import project into Eclipse without both files.

**Comment by Oen44** [comment]
Even creating new Java Project from existing source isn't helping.

**Comment by Arkhist** [comment]
No need, just import all projects inside the .zip

**Comment by Oen44** [comment]
The thing is, that Eclipse can't find any projects...
"No projects are found to import"

BTW. I did "git clone" rather than downloading as zip. But i'll try that.

**Comment by Arkhist** [comment]
You have to select "Projects from Folder or Archive"

**Comment by Oen44** [comment]
There is no such option.
http://screenshot.sh/odTuKB74TokHa

**Comment by Arkhist** [comment]
Hmmm, I think indeed the classpath and project files have been removed, at the time I downloaded the files they were on.

**Comment by Oen44** [comment]
That's what I'm saying. Waiting for skullb0x to get it back.

**Comment by skullb0x** [comment]
Re-added .project and .classpath file to project
