### ISSUE TITLE
Register server

### ISSUE THREAD

**Issue by adiif1** [skullb0x/bluesaga#35]
Why registration system is http://www.bluesaga.org/ whether it is possible to do registration with each separately?

**Comment by adiif1** [comment]
Refresh?

**Comment by skullb0x** [comment]
What do you mean exactly? You need to register the server at http://www.bluesaga.org in order for the players to be able to use forums and so on.

**Comment by adiif1** [comment]
He wants to account kept at my server

**Comment by skullb0x** [comment]
The reason the users are saved on bluesaga.org is so that users can play on all different servers with the same account. So that is why users shouldn't be split up on different servers. Only player characters are saved on the specific servers.
