### ISSUE TITLE
CreateCharacter should not blindly create characters

### ISSUE THREAD

**Issue by Titousensei** [skullb0x/bluesaga#40]
I'm creating test characters, and I did not notice those are sent to the website. Since I have to give a different name each time, (even when I delete them from userDB!), it gets tedious very fast.

1) none of those API calls should be sent in DEV_MODE. UpdateServerStatus is protected, but the others are not.
2) one should not be able to create a character for another serverID.  To protect against that, it might be necessary to give each serverID a password or a key.
3) there's no API to delete characters. Maybe it's a feature to avoid accidents. But if the userDB is deleted (on purpose or by accident), all the character data is lost, but users can't re-create their characters with the same names.

**Comment by skullb0x** [comment]
You're right, I will look into this!
